
services:
  backend: 
    build: .
    environment: 
      PORT: 8080
      POSTGRES_URL: postgres://tracking_service:password@db:5432/tracking_service
      LOCAL_ENV: 1
    ports: 
      - "8080:8080"

  db: 
    image: postgres:latest
    environment: 
      POSTGRES_USER: tracking_service
      POSTGRES_DB: tracking_service
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer: 
    image: adminer:latest
    ports: 
      - "8000:8080"
