
services:
  backend: 
    build: .
    environment: 
      PORT: 8080
      POSTGRES_URL: postgres://tracking_service:password@db:5432/tracking_service
      LOCAL_ENV: 1
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on: 
      migrate:
        condition: service_completed_successfully
    ports: 
      - "8080:8080"

  frontend:
    build: ./front
    ports:
      - "3000:80"

  migrate:
    image: migrate/migrate
    depends_on: 
      db:
        condition: service_healthy
    volumes:
      - ./internal/common/db/migrations:/migrations:ro
    command: 
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://tracking_service:password@db:5432/tracking_service?sslmode=disable"
      - "up"

  db: 
    image: postgres:latest
    environment: 
      POSTGRES_USER: tracking_service
      POSTGRES_DB: tracking_service
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"

  adminer: 
    image: adminer:latest
    depends_on: 
      - db
    ports: 
      - "8000:8080"
