// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        pgtype.UUID
	OccuredAt pgtype.Timestamp
	UserID    int64
	Action    string
	Metadata  []byte
}
